"""Generate the test-suite facts quoted in the README.

Same discipline as `generate_results.py`: the README quotes no number that a
committed script did not produce. A hand-typed test count is stale the moment
a test is added, and a stale number in a README is a small lie that teaches a
reader to trust none of the others.

What is committed here is machine-independent by construction. The test count
and the count of tests that touch the network are properties of the source
tree, identical on any machine and any Python. Wall-clock duration is
deliberately *not* recorded: it varies by machine, and committing it would
make CI's drift gate fail on a faster runner for no useful reason.

The network claim is the one worth generating rather than asserting by hand.
CI must never make a live call, and this script verifies that by collecting the
suite and checking that not one test is capable of opening a socket -- rather
than by someone remembering it is true.

Run:  python scripts/generate_test_report.py
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = RESULTS / "test-suite.md"

# Every module that could open a real socket. A test suite claiming to make no
# live calls must not import any of these outside an injected transport.
NETWORK_ENTRYPOINTS = (
    "httpx.AsyncHTTPTransport",
    "httpx.HTTPTransport",
    "socket.socket",
    "requests.",
    "urllib.request",
)


def collect() -> tuple[int, list[str]]:
    """Ask pytest what tests exist. Collection only -- nothing is executed."""
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "--no-header"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(f"pytest collection failed:\n{proc.stdout}\n{proc.stderr}")
    ids = [
        line.strip()
        for line in proc.stdout.splitlines()
        if "::" in line and not line.startswith(" ")
    ]
    return len(ids), ids


def run_suite() -> tuple[int, int]:
    """Run the suite. Returns (passed, failed)."""
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "--no-header"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    tail = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else ""
    passed = int(m.group(1)) if (m := re.search(r"(\d+) passed", tail)) else 0
    failed = int(m.group(1)) if (m := re.search(r"(\d+) failed", tail)) else 0
    return passed, failed


def audit_network_use() -> list[str]:
    """Find any test file that could reach the network.

    The check is deliberately crude and errs toward false positives: a
    suspicious import is cheap to explain and a missed live call is a billed,
    flaky CI run.
    """
    offenders: list[str] = []
    for path in sorted((ROOT / "tests").glob("test_*.py")):
        text = path.read_text(encoding="utf-8")
        for marker in NETWORK_ENTRYPOINTS:
            if marker in text:
                offenders.append(f"{path.name}: {marker}")
    return offenders


def main() -> None:
    RESULTS.mkdir(exist_ok=True)
    total, ids = collect()
    passed, failed = run_suite()
    offenders = audit_network_use()

    # The claim CI depends on. Asserted here so a test that starts dialling out
    # fails this script -- and therefore the drift gate -- rather than quietly
    # billing someone.
    if offenders:
        raise SystemExit(
            "a test can reach the network, which breaks the no-live-calls "
            f"guarantee: {offenders}"
        )
    if failed:
        raise SystemExit(f"{failed} test(s) failing; not writing a green report")
    if passed != total:
        raise SystemExit(f"collected {total} tests but only {passed} passed")

    per_file: dict[str, int] = {}
    for tid in ids:
        per_file[tid.split("::")[0].replace("\\", "/")] = (
            per_file.get(tid.split("::")[0].replace("\\", "/"), 0) + 1
        )

    L: list[str] = []
    add = L.append
    add("# Test suite: what is covered, and what it never touches\n")
    add("Generated by `python scripts/generate_test_report.py`. Do not edit by hand.\n")
    add("Counts are properties of the source tree, so they are identical on")
    add("any machine. Wall-clock duration is deliberately not recorded here:")
    add("it varies by runner and would make the drift gate fail for no useful")
    add("reason.\n")
    add(f"- **{passed} tests, all passing**")
    add("- Reproduce: `python -m pytest -q`\n")
    add("## Where the tests are\n")
    add("| file | tests |")
    add("|---|---|")
    for name, count in sorted(per_file.items()):
        add(f"| `{name}` | {count} |")
    add("")
    add("## No test makes a live API call\n")
    add("Asserted by this script, which fails if any test file references a")
    add("real transport (`httpx.AsyncHTTPTransport`, `socket`, `requests`,")
    add("`urllib.request`). Every test drives the real client over an injected")
    add("`httpx.MockTransport` or a recorded cassette, so the retry loop,")
    add("timeouts and pooling under test are the real ones and only the socket")
    add("is replaced.\n")
    add("This is a design requirement rather than a convenience: a suite whose")
    add("result depends on a third party's uptime and a non-deterministic")
    add("sampler is a status page, not a test suite.\n")
    add("## Limitations\n")
    add("- **Test count is not coverage.** This file says how many tests exist")
    add("  and that none dials out. It says nothing about which branches they")
    add("  reach; no coverage measurement is committed here.")
    add("- The network audit is a static grep over test files. It would not")
    add("  catch a live call made from a helper imported out of `src/`.")
    add("- Cassettes prove the client parses what a server *did* send, not that")
    add("  any provider still sends it. A re-record is the only way to know.\n")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({passed} tests)")
    print(json.dumps(per_file, indent=2))


if __name__ == "__main__":
    main()
